/*

[Diagram]

Editing : Enter the program in the computer.

Pre-Processing : 
    - (a) Macro Substitution
    - (b) Comments are stripped off.
    - (c) Expansion of included files.

Compiling : Textual src into machine code [1's and 0's]

Linking : A program that takes one or more than one object files generated by compiler and combines them into one.

Executing the loadable image : Loader image -> Loads image into memory.asm

./a.exe (Windows)
./a.out (Unix)

*/